dist: trusty
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
before_script:
  - npm run clean
script:
  - npm run test
  - npm run lint
after_script:
  - npm run coveralls
before_deploy:
  - npm run clean
  - npm run build
